version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend

  backend:
    build: ./backend
    container_name: backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
